name: solubility-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - rdkit
  - scikit-learn
  - pandas
  - numpy
  - joblib
  - matplotlib
  - pillow
  - pip
  - pip:
      - streamlit
      - xgboost
      - shap
